# Generated by Django 3.1.1 on 2020-09-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tproducts', '0003_auto_20200919_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='tproduct',
            name='contact',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
