# Generated by Django 3.1.1 on 2020-09-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tproducts', '0004_tproduct_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='tproduct',
            name='address',
            field=models.CharField(default='not provided', max_length=255),
        ),
    ]
